version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - id: zetten-cli
    env:
      - CGO_ENABLED=0
    binary: zetten-cli
    main: ./cmd/cli
  - id: zetten-service
    env:
      - CGO_ENABLED=0
    binary: zetten-service
    main: ./cmd/service

archives:
  - formats: [tar.gz]
    ids:
      - zetten-cli
      - zetten-service
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - scripts/install.sh
      - scripts/install.bat

    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
